/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#00513f',
        'secondary-fixed-dim': '#4ae176',
        'primary-container': '#00ffcc',
        primary: '#fdfffc',
        error: '#ffb4ab',
        'on-tertiary-fixed': '#410004',
        'primary-fixed': '#24ffcd',
        'on-primary-container': '#00725a',
        'tertiary-container': '#ffd9d6',
        'outline-variant': '#3a4a44',
        background: '#131313',
        'on-surface-variant': '#b9cbc2',
        'surface-variant': '#353534',
        'on-background': '#e5e2e1',
        'primary-fixed-dim': '#00e0b3',
        'on-secondary-fixed': '#002109',
        'surface-container-lowest': '#0e0e0e',
        'surface-bright': '#3a3939',
        secondary: '#4ae176',
        'on-tertiary-fixed-variant': '#930013',
        'on-primary-fixed': '#002118',
        'tertiary-fixed-dim': '#ffb3ad',
        'on-tertiary-container': '#c22129',
        'on-surface': '#e5e2e1',
        'error-container': '#93000a',
        'secondary-fixed': '#6bff8f',
        'tertiary-fixed': '#ffdad7',
        'secondary-container': '#00b954',
        'on-primary': '#00382b',
        'surface-dim': '#131313',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#006b54',
        'on-secondary-fixed-variant': '#005321',
        surface: '#131313',
        'surface-container-highest': '#353534',
        'surface-container-high': '#2a2a2a',
        'on-secondary': '#003915',
        'inverse-surface': '#e5e2e1',
        'on-error-container': '#ffdad6',
        'surface-tint': '#00e0b3',
        outline: '#83958d',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        tertiary: '#fffeff',
        'on-tertiary': '#68000a',
        'on-error': '#690005',
        'on-secondary-container': '#004119',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '16px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'container-max': '1200px',
        'stack-sm': '8px',
        gutter: '24px',
      },
      fontFamily: {
        'code-block': ['JetBrains Mono', 'monospace'],
        'body-main': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'code-block': ['14px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'body-main': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
